### ISSUE TITLE
BUG: Playdium output invalid MIDI velocity

### ISSUE THREAD

**Issue by X-Raym** [analogmad/reaper#1]
Hi,

It seems playdium JS can sometimes output velocities beyond 127

These doesnt trigger sounds in R5k.

Thx!

**Comment by analogmad** [comment]
Thanks for the report. Will take a look this weekend and figure out what is
causing it to go over the max velocity of 127 in some cases.

Also thanks for checking out my script/js Raymond! You are a legend. :)

**Comment by X-Raym** [comment]
haha, many thanks  🙏🥰

When you will update, you will be able to keep only one [@changelog](
https://github.com/cfillion/reapack-index/wiki/Packaging-Documentation#changelog) declaration on top of the JSFX (they are 3 currently).

Good luck with the bug fix! 🖖

**Comment by analogmad** [comment]
Finally had some time after many many months to look at the Velocity Range. I put in a check to ensure that the velocity range always stays between the vel_low and vel_high ranges. So it can never go out of range. Just committed a version 1.4 update. Cleaned up the older 3 declarations. After hours of testing. It no longer goes out of Velocity range.

**Comment by analogmad** [comment]
Updated JSFX to version 1.4 with a fix

`// Generate a random velocity without repeating the recent history
function random_velocity() (
  sample_range = (127 - 0 + 1) / num_samples;

  new_velocity = vel_low + floor(rand(num_samples) * sample_range) + floor(rand(sample_range));
  while (new_velocity > vel_high) (
    new_velocity = vel_low + floor(rand(num_samples) * sample_range) + floor(rand(sample_range));
  );
  new_velocity;
);`
